### ISSUE TITLE
index.html is doesn't load any maps 

### ISSUE THREAD

**Issue by skorasaurus** [tangrams/multiverse#2]
Visit http://tangrams.github.io/multiverse/

What I Saw: 
a line of text - "Cartographic explorations using tangram.js 2D/3D map engine for Mapzen."

Expectation: 
I expected to see a few base maps here 
(Is that the purpose of this repository? It was pinned on the tangrams github page and I was curious) 
 
Error is caused 
https://github.com/tangrams/multiverse/blob/gh-pages/index.html#L7 tries to load src/glslCanvas.js which isn't in this repository and gives a 404 error. 

Perhaps this repository has been superseded by another one?

**Comment by nvkelso** [comment]
@meetar Can you take a look, please?

**Comment by meetar** [comment]
Well, there's definitely a missing file, but replacing the file doesn't change anything. Looks like this was a @patriciogonzalezvivo joint – I'll pass the buck to him.

**Comment by patriciogonzalezvivo** [comment]
This was an early @sensescape's sandbox, she seams to fork `tangram-sandbox` for it, lefting behind a reference to `glslCanvas.js` that is not there any more. (I just take it out, thanks)

This sandbox doesn't have a "gallery" but it was styles that could be load in a similar way than `tangram-sandbox`

**Comment by meetar** [comment]
This repo was mostly a repository for some of the maps in this post:

https://mapzen.com/blog/lines/

…all of which were loaded inside a tangram-frame, like this:

https://tangrams.github.io/tangram-frame/?url=https://raw.githubusercontent.com/tangrams/multiverse/gh-pages/styles/airports.yaml#13/37.6189/-122.3765

@skorasaurus, you can check out the styles which aren't featured in the lines post by modifying the url above. Hope this clears things up, and thanks for checking!
